### ISSUE TITLE
希望能有个赞助方式

### ISSUE THREAD

**Issue by YangHeng1999** [juzeon/advanced-php-crawler#1]
如今新浪博客不能新注册账号，在app上就看不到博文了，对程序一窍不通，有幸遇到这个神器，对我帮助非常大。希望能有一个捐助方式，略尽心意，谢谢！

**Comment by juzeon** [comment]
请仔细看说明，需要配合sina-list使用。

如果您的问题已经解决，请关闭此issue。

**Comment by YangHeng1999** [comment]
感谢您的教程和程序，是我的错，祝您六时吉祥

**Comment by YangHeng1999** [comment]
php sina-list.php 句子提供.txt 
句子提供.txt里面的目录网址是在手机复制进去的，放到电脑里网址后面加个回车就好了
